/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BDPuntoVentaManuel.Views.Product;


import BDPuntoVentaManuel.MODEL.Catcategoria;
import com.mysql.jdbc.StringUtils;
import java.awt.event.ItemEvent;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author manuel
 */
public class Products_Default extends javax.swing.JPanel {

    /**
     * Creates new form Products_Default
     */
    public Products_Default() {
        initComponents();
        this.Windows_Start();
    }
    
    private void Windows_Start()
    {
        this.Data_Default();
    }
    
    private void Data_Default()
    {
        Products_Start.ProductsProcess=new Products();
        this.cmbCategoria.setModel(Products_Start.ProductsProcess.getModelCategorias());
        this.lbErrorMEssage.setVisible(false);
        
        this.ResetDataTable();
        
    }
    
    private void SetModelTable()
    {
        modelTab=new DefaultTableModel();
        modelTab.addColumn("Codigo");
        modelTab.addColumn("Nombre");
        modelTab.addColumn("Precio de compra");
        modelTab.addColumn("Precio de venta");
        modelTab.addColumn("Stock");
        modelTab.addColumn("Descripcion");
        modelTab.addColumn("Presentcion");
    }

    public void ResetDataTable()
    {
        if(categoria !=null && categoria.getId()>0)
        {
            this.SetModelTable();
            Products_Start.ProductsProcess.ChargeDataByCategoriaId(modelTab, categoria);
            this.tbData.setModel(modelTab);
        }
        if(categoria==null || categoria.getId()<=0)
        {
            this.SetModelTable();
            Products_Start.ProductsProcess.ChargeDataDefault(modelTab);
            this.tbData.setModel(modelTab);
        }
    }
    
    private void ResetDataTableBySearch()
    {
            this.SetModelTable();
            Products_Start.ProductsProcess.SearchProductByLette(this.txtNombre.getText().trim(),
                    modelTab);
            this.tbData.setModel(modelTab);
    }
    
    private void PainErrorMessage()
    {
        this.lbErrorMEssage.setText("Es necesario llenar el campo nombre");
        this.lbErrorMEssage.setVisible(true);
    }
    private void CleanErrorMessage()
    {
        this.lbErrorMEssage.setVisible(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbCategoria = new javax.swing.JComboBox();
        txtNombre = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbErrorMEssage = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbData = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(925, 297));

        cmbCategoria.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbCategoriaItemStateChanged(evt);
            }
        });

        btnSearch.setText("Buscar");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        jLabel2.setText("Categoria del producto");

        jLabel3.setText("Nombre");

        lbErrorMEssage.setForeground(new java.awt.Color(255, 0, 0));
        lbErrorMEssage.setText("ErrorMessage");

        tbData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tbData);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(43, 43, 43)
                        .addComponent(cmbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(41, 41, 41)
                                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lbErrorMEssage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbErrorMEssage)
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    private void cmbCategoriaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbCategoriaItemStateChanged
       if(evt.getStateChange()==ItemEvent.SELECTED)
        {
            categoria =(Catcategoria) this.cmbCategoria.getSelectedItem();
            this.ResetDataTable();
        }
    }//GEN-LAST:event_cmbCategoriaItemStateChanged

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
//        String result;
        if(!StringUtils.isNullOrEmpty(this.txtNombre.getText()))
        {
            CleanErrorMessage();
            ResetDataTableBySearch();
        }else
        {
            PainErrorMessage();
        }
    }//GEN-LAST:event_btnSearchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox cmbCategoria;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbErrorMEssage;
    private javax.swing.JTable tbData;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
    
//    //Variables
    private DefaultTableModel modelTab;
    private Catcategoria categoria=null;
}
