/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BDPuntoVentaManuel.Views.Product;


import BDPuntoVentaManuel.MODEL.Product;
import com.mysql.jdbc.StringUtils;
import javax.swing.JOptionPane;

/**
 *
 * @author manuel
 */
public class Products_Select_Innabilit extends javax.swing.JPanel {

    /**
     * Creates new form Products_SelectProduct
     */
    public Products_Select_Innabilit() {
        initComponents();
    }

     public void Open_Update() {
        this.btnProcess.setText("Siguiente");

        this.Clean_Windows();
        this.setVisible(true);
    }

    private void Clean_Windows() {
        this.txtCodigo.setText(null);

        this.lbErro1.setVisible(false);
        this.lbErrorMessage.setVisible(false);
    }

    private void Paint_ErrorMessage(String MEssage) {
        this.lbErro1.setVisible(true);

        this.lbErrorMessage.setText(MEssage);
        this.lbErrorMessage.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        btnProcess = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        lbErro1 = new javax.swing.JLabel();
        lbErrorMessage = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setForeground(new java.awt.Color(51, 204, 255));
        jLabel1.setText("Ingresar codigo del producto");

        txtCodigo.setForeground(new java.awt.Color(51, 204, 255));

        btnProcess.setBackground(new java.awt.Color(255, 255, 255));
        btnProcess.setForeground(new java.awt.Color(51, 204, 255));
        btnProcess.setText("Process");
        btnProcess.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnProcess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcessActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(255, 255, 255));
        btnCancelar.setForeground(new java.awt.Color(51, 204, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        lbErro1.setForeground(new java.awt.Color(255, 51, 51));
        lbErro1.setText("*");

        lbErrorMessage.setForeground(new java.awt.Color(255, 51, 51));
        lbErrorMessage.setText("Error");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbErrorMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(246, 246, 246)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnCancelar)
                                .addGap(175, 175, 175)
                                .addComponent(btnProcess))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(53, 53, 53)
                                .addComponent(lbErro1, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(246, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbErro1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbErrorMessage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProcess)
                    .addComponent(btnCancelar))
                .addGap(83, 83, 83))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnProcessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcessActionPerformed
//        if (btnProcess.getText().equals("Siguiente")) {
            if (!StringUtils.isNullOrEmpty(this.txtCodigo.getText())) {
                String Codigo = txtCodigo.getText().trim();
                Product item = Products_Start.ProductsProcess.GetProductByCode(Codigo);

                if (item != null) {
                    Products_Start.viewProduct.Open_Windows_Update(item);
                    Products_Start.viewSelect.setVisible(false);
                    Products_Start.viewDefault.setVisible(false);

                } else {
                    this.Paint_ErrorMessage("No existe en tu repletorio un producto con el codigo ingresado");
                }

            } else {
                this.Paint_ErrorMessage("Es necesario ingresar el codigo del producto");
            }

    }//GEN-LAST:event_btnProcessActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        Products_Start.viewProduct.setVisible(false);
        Products_Start.viewSelect.setVisible(false);
        Products_Start.viewDefault.setVisible(true);
    }//GEN-LAST:event_btnCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnProcess;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbErro1;
    private javax.swing.JLabel lbErrorMessage;
    private javax.swing.JTextField txtCodigo;
    // End of variables declaration//GEN-END:variables

}
