/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BDPuntoVentaManuel.Views.Orders;


import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;

/**
 *
 * @author manuel
 */
public class Orders_Start extends javax.swing.JInternalFrame {

    /**
     * Creates new form Orders_Start
     */
    public Orders_Start() {
        initComponents();
        this.Start_Windows();
    }
    private void Start_Windows()
    {
        this.Start_Connections();
        this.Close_Views();
        this.Open_COnfigVindowsDefault();
    }

    private void Start_Connections()
    {
        System.out.println("Inicializado");
        OrdersProcess=new Orders();
        
        viewOrders=new Orders_New_Update();
        viewSelect=new Orders_Select_Cancel();
        viewDefault=new Orders_Default();
        viewProcess=new Orders_Process();
        
        pnContainer.setLayout(Layout);
        GridBagConstraints cons= new GridBagConstraints();
        
        cons.gridx=0;
        cons.gridy=0;
        
        pnContainer.add(viewOrders,cons);
        pnContainer.add(viewSelect,cons);
        pnContainer.add(viewDefault,cons);
        pnContainer.add(viewProcess,cons);

    }
    
    private void Open_COnfigVindowsDefault()
    {
        viewOrders.setVisible(false);
        viewSelect.setVisible(false);
        viewDefault.setVisible(true);
        viewProcess.setVisible(false);
    }
    
    private void Close_Views()
    {
        viewOrders.setVisible(false);
        viewSelect.setVisible(true);
        this.viewDefault.setVisible(false);
        viewProcess.setVisible(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnContainer = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnExit = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        btnNew = new javax.swing.JMenuItem();
        btnCancel = new javax.swing.JMenuItem();
        btnReception = new javax.swing.JMenuItem();

        javax.swing.GroupLayout pnContainerLayout = new javax.swing.GroupLayout(pnContainer);
        pnContainer.setLayout(pnContainerLayout);
        pnContainerLayout.setHorizontalGroup(
            pnContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnContainerLayout.setVerticalGroup(
            pnContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 353, Short.MAX_VALUE)
        );

        btnExit.setText("Salir");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(875, Short.MAX_VALUE)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnExit)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jMenu1.setText("Ordenes");

        btnNew.setText("Nueva orden");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });
        jMenu1.add(btnNew);

        btnCancel.setText("Cancelar orden");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        jMenu1.add(btnCancel);

        btnReception.setText("Recepcio del producto");
        btnReception.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReceptionActionPerformed(evt);
            }
        });
        jMenu1.add(btnReception);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
         viewOrders.setVisible(true);
        viewSelect.setVisible(false);
        viewDefault.setVisible(false);
        viewProcess.setVisible(false);
    }//GEN-LAST:event_btnNewActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        viewOrders.setVisible(false);
        viewSelect.setVisible(true);
        viewDefault.setVisible(false);
        viewProcess.setVisible(false);
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnReceptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReceptionActionPerformed
        viewOrders.setVisible(false);
        viewSelect.setVisible(true);
        viewDefault.setVisible(false);
        viewProcess.setVisible(false);
    }//GEN-LAST:event_btnReceptionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btnCancel;
    private javax.swing.JButton btnExit;
    private javax.swing.JMenuItem btnNew;
    private javax.swing.JMenuItem btnReception;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel pnContainer;
    // End of variables declaration//GEN-END:variables

    //View orders
    public static Orders_New_Update viewOrders;
    public static Orders_Select_Cancel viewSelect;
    public static Orders_Default viewDefault;
    public static Orders_Process viewProcess;
    
    //Variables
    GridBagLayout Layout=new GridBagLayout();
    
    //Variable de procesos
    public static Orders OrdersProcess;
}
