/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BDPuntoVentaManuel.Views.Request;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultListModel;

/**
 *
 * @author manuel
 */
public class Request_Partial extends javax.swing.JPanel {

    /**
     * Creates new form Request_Partial
     */
    public Request_Partial() {
        initComponents();
        this.lbErrorMessage.setVisible(false);
    }
    
    public void OpenWindows(int folio)
    {
        BDPuntoVentaManuel.MODEL.Request request=Request_Start.RequestProcess.GetRequestByFolio(folio);
        this.ChargeData(request);
         
        Request_Start.viewRequest.setVisible(false);
        Request_Start.pnOptions.setVisible(false);
        Request_Start.viewDefault.setVisible(false);
        Request_Start.viewProcess.setVisible(false);
        Request_Start.viewPartial.setVisible(true);
        Request_Start.viewValid.setVisible(false);
    }
    
    private void ChargeData(BDPuntoVentaManuel.MODEL.Request request)
    {
           
        SimpleDateFormat date = new SimpleDateFormat("dd-MM-yyyy");

        this.lbDate.setText(date.format(request.getDatFecha()));
        this.lbEmail.setText(request.getIdSuplier().getIdContacto().getStrEmail());
        this.lbSupplier.setText(request.getIdSuplier().getStrBussinessName());
        this.lbTotal.setText("$"+request.getDoubTotal());
        this.lbFolio.setText(request.getId().toString());
        
        this.listProduct1.setModel(Request_Start.RequestProcess.getModelListProduct(request));
        this.listProduct2.setModel(Request_Start.RequestProcess.getModelListProductNull());

    }
    
    private void ChargeProductToPo()
    {
        DefaultListModel lm1=(DefaultListModel) this.listProduct1.getModel();
        DefaultListModel lm2=(DefaultListModel) this.listProduct2.getModel();
        
        BDPuntoVentaManuel.MODEL.Requestdetail product=(BDPuntoVentaManuel.MODEL.Requestdetail)lm1.getElementAt(this.listProduct1.getSelectedIndex());
        
        lm1.removeElement(product);
        lm2.addElement(product);
        
        this.listProduct1.setModel(lm1);
        this.listProduct2.setModel(lm2);
        
    }

    private void DeleteProductToPo()
    {
        DefaultListModel lm1=(DefaultListModel) this.listProduct1.getModel();
        DefaultListModel lm2=(DefaultListModel) this.listProduct2.getModel();
        
        BDPuntoVentaManuel.MODEL.Requestdetail product=(BDPuntoVentaManuel.MODEL.Requestdetail)lm2.getElementAt(this.listProduct2.getSelectedIndex());
        
        lm2.removeElement(product);
        lm1.addElement(product);
        
        this.listProduct1.setModel(lm1);
        this.listProduct2.setModel(lm2);
        
    }
    
    private void PaintErrorMessage(String message)
    {
        this.lbErrorMessage.setText(message);
        this.lbErrorMessage.setVisible(true);
    }
    private void CleanErrorMessage()
    {
        this.lbErrorMessage.setVisible(false);
    }
    private List<BDPuntoVentaManuel.MODEL.Requestdetail> getListProducts()
    {
        List<BDPuntoVentaManuel.MODEL.Requestdetail> listRequestDetails=new ArrayList();
        DefaultListModel lm2=(DefaultListModel) this.listProduct2.getModel();

        for (int i = 0; i < lm2.size(); i++) {
            listRequestDetails.add((BDPuntoVentaManuel.MODEL.Requestdetail)
                    lm2.getElementAt(i));
        }
        return listRequestDetails;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbSupplier = new javax.swing.JLabel();
        lbEmail = new javax.swing.JLabel();
        lbDate = new javax.swing.JLabel();
        lbTotal = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listProduct1 = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        listProduct2 = new javax.swing.JList();
        btnNext = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnGenerar = new javax.swing.JButton();
        lbErrorMessage = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lbFolio = new javax.swing.JLabel();

        jLabel1.setText("Provedor");

        jLabel2.setText("Email");

        jLabel3.setText("Fecha");

        jLabel4.setText("Total general");

        lbSupplier.setText("jLabel5");

        lbEmail.setText("jLabel6");

        lbDate.setText("jLabel7");

        lbTotal.setText("jLabel8");

        jScrollPane1.setViewportView(listProduct1);

        jScrollPane2.setViewportView(listProduct2);

        btnNext.setText(">");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnBack.setText("<");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnGenerar.setText("Generar orden de compra");
        btnGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarActionPerformed(evt);
            }
        });

        lbErrorMessage.setForeground(new java.awt.Color(204, 0, 0));
        lbErrorMessage.setText("jLabel9");

        jLabel5.setText("Folio");

        lbFolio.setText("jLabel6");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGenerar)
                .addGap(364, 364, 364))
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbErrorMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnNext)
                                    .addComponent(btnBack)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(lbFolio, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lbEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                                        .addComponent(lbSupplier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbTotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbDate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(29, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lbFolio))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(lbSupplier)
                    .addComponent(lbDate))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(lbEmail)
                    .addComponent(lbTotal))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(btnNext)
                        .addGap(18, 18, 18)
                        .addComponent(btnBack)))
                .addGap(18, 18, 18)
                .addComponent(lbErrorMessage)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGenerar)
                    .addComponent(btnCancelar))
                .addContainerGap(26, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        Request_Start.viewRequest.setVisible(false);
        Request_Start.pnOptions.setVisible(false);
        Request_Start.viewDefault.setVisible(false);
        Request_Start.viewProcess.setVisible(false);
        Request_Start.viewPartial.setVisible(false);
        Request_Start.viewValid.setVisible(true);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarActionPerformed
        if (visitError) {
            CleanErrorMessage();
        }
        List<BDPuntoVentaManuel.MODEL.Requestdetail> listRequestDetails=this.getListProducts();
        if (listRequestDetails.size() > 0) {
            int folio = Integer.parseInt(this.lbFolio.getText());
            if (Request_Start.RequestProcess.CreatePartialPO(listRequestDetails, folio)) {
                Request_Start.viewRequest.setVisible(false);
                Request_Start.pnOptions.setVisible(true);
                Request_Start.viewDefault.setVisible(true);
                Request_Start.viewDefault.ChargeDataTable();
                Request_Start.viewProcess.setVisible(false);
                Request_Start.viewPartial.setVisible(false);
                Request_Start.viewValid.setVisible(false);
            }
        } else {
            this.PaintErrorMessage("Es necesario ingresar al menos un elemento a la orden de compra");
        }


    }//GEN-LAST:event_btnGenerarActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        if(visitError)
        {
            CleanErrorMessage();
        }
        if(this.listProduct1.getSelectedIndex()>=0)
        {
        this.ChargeProductToPo();
        }else{
            PaintErrorMessage("Es necesario seleccionar un producto");
        }
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        if(visitError)
        {
            CleanErrorMessage();
        }
        
        if(this.listProduct2.getSelectedIndex()>=0)
        {
        this.DeleteProductToPo();
        }else{
            PaintErrorMessage("Es necesario seleccionar un producto");
        }
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGenerar;
    private javax.swing.JButton btnNext;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbDate;
    private javax.swing.JLabel lbEmail;
    private javax.swing.JLabel lbErrorMessage;
    private javax.swing.JLabel lbFolio;
    private javax.swing.JLabel lbSupplier;
    private javax.swing.JLabel lbTotal;
    private javax.swing.JList listProduct1;
    private javax.swing.JList listProduct2;
    // End of variables declaration//GEN-END:variables

    //Variables
    private boolean visitError=false;

}
