/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BDPuntoVentaManuel.Views.Supplier;

import BDPuntoVentaManuel.MODEL.Supplier;
import com.mysql.jdbc.StringUtils;

/**
 *
 * @author manuel
 */
public class Suppliers_Select_Innabilit extends javax.swing.JPanel {

    /**
     * Creates new form Suppliers_Select_Innabilit
     */
    public Suppliers_Select_Innabilit() {
        initComponents();
    }
    
    public void Open_Update() {
        this.btnProcess.setText("Siguiente");

        this.Clean_Windows();
        this.setVisible(true);
    }

    private void Clean_Windows() {
        this.txtCodigo.setText(null);

        this.lbErro1.setVisible(false);
        this.lbErrorMessage.setVisible(false);
    }

    private void Paint_ErrorMessage(String MEssage) {
        this.lbErro1.setVisible(true);

        this.lbErrorMessage.setText(MEssage);
        this.lbErrorMessage.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnProcess = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txtCodigo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lbErrorMessage = new javax.swing.JLabel();
        lbErro1 = new javax.swing.JLabel();

        btnProcess.setText("Process");
        btnProcess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcessActionPerformed(evt);
            }
        });

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("Ingresar codigo del provedor");

        lbErrorMessage.setForeground(new java.awt.Color(255, 51, 51));
        lbErrorMessage.setText("Error");

        lbErro1.setForeground(new java.awt.Color(255, 51, 51));
        lbErro1.setText("*");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addComponent(jButton2)
                .addGap(175, 175, 175)
                .addComponent(btnProcess)
                .addContainerGap(178, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbErrorMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(53, 53, 53)
                        .addComponent(lbErro1, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(87, 87, 87))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbErro1))
                .addGap(27, 27, 27)
                .addComponent(lbErrorMessage)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProcess)
                    .addComponent(jButton2))
                .addGap(17, 17, 17))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnProcessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcessActionPerformed
        //        if (btnProcess.getText().equals("Siguiente")) {
            if (!StringUtils.isNullOrEmpty(this.txtCodigo.getText())) {
                String Codigo = txtCodigo.getText().trim();
                Supplier item = Suppliers_Start.SuppliersProcess.GetSupplierByCode(Codigo);

                if (item != null) {
                   Suppliers_Start.viewSupplier.Open_Windows_Update(item);
                   Suppliers_Start.viewSelect.setVisible(false);
                   Suppliers_Start.viewDefault.setVisible(false);

                } else {
                    this.Paint_ErrorMessage("No existe en tu repletorio un producto con el codigo ingresado");
                }

            } else {
                this.Paint_ErrorMessage("Es necesario ingresar el codigo del producto");
            }
    }//GEN-LAST:event_btnProcessActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Suppliers_Start.viewSupplier.setVisible(false);
        Suppliers_Start.viewSelect.setVisible(false);
        Suppliers_Start.viewDefault.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnProcess;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbErro1;
    private javax.swing.JLabel lbErrorMessage;
    private javax.swing.JTextField txtCodigo;
    // End of variables declaration//GEN-END:variables

    //Vistas del provedor
    

}
